/*
 * Copyright (C) 2021 - 2026, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: fyfej
 * Date: 2023-6-21
 */
using Hl7.Fhir.Model;
using RestSrvr;
using SanteDB.Core;
using SanteDB.Core.Diagnostics;
using SanteDB.Core.Interop;
using SanteDB.Core.Services;
using SanteDB.Messaging.FHIR.Configuration;
using SanteDB.Messaging.FHIR.Handlers;
using SanteDB.Messaging.FHIR.Rest;
using SanteDB.Rest.Common;
using SanteDB.Rest.Common.Behavior;
using SanteDB.Rest.Common.Configuration;
using System;
using System.Collections.Generic;
using System.Diagnostics.Tracing;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using static Hl7.Fhir.Model.CapabilityStatement;

namespace SanteDB.Messaging.FHIR.Util
{
    /// <summary>
    /// Conformance utility
    /// </summary>
    public static class ConformanceUtil
    {
        // Conformance built
        private static CapabilityStatement s_conformance;

        // Sync lock
        private static readonly object s_syncLock = new object();

        // FHIR trace source
        private static readonly Tracer s_traceSource = new Tracer(FhirConstants.TraceSourceName);

        // Configuration section
        private static readonly FhirServiceConfigurationSection s_configuration = ApplicationServiceContext.Current.GetService<IConfigurationManager>().GetSection<FhirServiceConfigurationSection>();

        /// <summary>
        /// Get Conformance Statement from FHIR service
        /// </summary>
        public static CapabilityStatement GetConformanceStatement()
        {
            if (s_conformance == null)
            {
                lock (s_syncLock)
                {
                    BuildConformanceStatement();
                    RestOperationContext.Current.OutgoingResponse.SetLastModified(DateTime.Now);
                }
            }

            return s_conformance;
        }

        /// <summary>
        /// Build conformance statement
        /// </summary>
        private static void BuildConformanceStatement()
        {
            try
            {

                // No output of any exceptions
                Assembly entryAssembly = Assembly.GetEntryAssembly() ?? typeof(ConformanceUtil).Assembly;

                // First assign the basic attributes
                s_conformance = new CapabilityStatement()
                {
                    Software = new SoftwareComponent()
                    {
                        Name = entryAssembly?.GetCustomAttribute<AssemblyProductAttribute>().Product ?? "SanteDB",
                        Version = entryAssembly?.GetName().Version.ToString() ?? "3.0-general"
                    },
                    DateElement = new FhirDateTime(DateTimeOffset.Now),
                    Description = new Markdown("Automatically generated by ServiceCore FHIR framework"),
                    Experimental = true,
                    FhirVersion = FHIRVersion.N4_1_0,
                    Format = new List<string>() { "xml", "json" },
                    Implementation = new ImplementationComponent()
                    {
                        Url = s_configuration.ResourceBaseUri,
                        Description = typeof(ConformanceUtil).Assembly.GetCustomAttribute<AssemblyDescriptionAttribute>().Description
                    },
                    Name = "SVC-CORE FHIR",
                    Publisher = entryAssembly?.GetCustomAttribute<AssemblyCompanyAttribute>().Company ?? "SanteSuite Inc.",
                    Title = $"Auto-Generated statement - {entryAssembly?.GetCustomAttribute<AssemblyProductAttribute>()?.Product} v{entryAssembly?.GetName().Version} ({entryAssembly?.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion})",
                    Status = PublicationStatus.Active,
                    Copyright = new Markdown(entryAssembly.GetCustomAttribute<AssemblyCopyrightAttribute>()?.Copyright)
                };

                // Generate the rest description
                // TODO: Reflect the current WCF context and get all the types of communication supported
                var restConfig = ApplicationServiceContext.Current.GetService<IConfigurationManager>().GetSection<RestConfigurationSection>();
                var fhirConfig = restConfig.Services.First(o => o.ServiceType == typeof(FhirServiceBehavior));
                s_conformance.Rest.AddRange(fhirConfig.Endpoints.Select(e=>CreateRestDefinition(e)));
                s_conformance.Messaging.Add(new MessagingComponent()
                {
                    Endpoint = fhirConfig.Endpoints.Select(e =>
                    {
                        var uriB = new UriBuilder(e.Address);
                        if (Uri.TryCreate(s_configuration.ResourceBaseUri, UriKind.Absolute, out var externalUri) ||
                            Uri.TryCreate(restConfig.ExternalHostPort, UriKind.Absolute, out externalUri))
                        {
                            uriB.Host = externalUri.Host;
                            uriB.Port = externalUri.Port;
                            uriB.Scheme = externalUri.Scheme;
                        }

                        return new EndpointComponent()
                        {
                            Address = uriB.ToString()
                        };
                    }).ToList(),
                    SupportedMessage = ExtensionUtil.GetMessageOperations().ToList()
                });
                s_conformance.Text = null;
            }
            catch (Exception e)
            {
                s_traceSource.TraceEvent(EventLevel.Error, "Error building conformance statement: {0}", e.Message);
                throw;
            }
        }

        /// <summary>
        /// Rest definition creator
        /// </summary>
        private static RestComponent CreateRestDefinition(RestEndpointConfiguration configuration)
        {

            // Security settings
            String security = null;
            //var m_masterConfig = ApplicationServiceContext.Current.GetService<IConfigurationManager>().GetSection<RestConfigurationSection>();
            //var authorizationPolicy = m_masterConfig.Services.FirstOrDefault(o => o.Name == "FHIR").Behaviors.Select(o => o.GetCustomAttribute<AuthenticationSchemeDescriptionAttribute>()).FirstOrDefault(o => o != null)?.Scheme;
            if (ApplicationServiceContext.Current.GetService<FhirMessageHandler>().Capabilities.HasFlag(ServiceEndpointCapabilities.BasicAuth))
            {
                security = "Basic";
            }

            if (ApplicationServiceContext.Current.GetService<FhirMessageHandler>().Capabilities.HasFlag(ServiceEndpointCapabilities.BearerAuth))
            {
                security = "OAuth";
            }

            var retVal = new RestComponent()
            {
                Mode = RestfulCapabilityMode.Server,
                Documentation = new Markdown("SanteDB REST Instance"),
                Security = new SecurityComponent()
                {
                    Cors = configuration.Behaviors.Any(r=>r.Type == typeof(CorsEndpointBehavior)),
                    Service = security == null ? null : new List<CodeableConcept>() { new CodeableConcept("http://hl7.org/fhir/restful-security-service", security) }
                },
                Resource = FhirResourceHandlerUtil.GetRestDefinition().ToList(),
                Operation = ExtensionUtil.OperationHandlers.Where(o => o.AppliesTo == null).Select(o => new OperationComponent()
                {
                    Name = o.Name,
                    Definition = o.Uri.ToString()
                }).ToList()
            };

            foreach (var itm in retVal.Resource)
            {
                itm.Operation = ExtensionUtil.OperationHandlers.Where(o => o.AppliesTo?.Contains(itm.Type.Value) == true).Select(o => new OperationComponent()
                {
                    Name = o.Name,
                    Definition = o.Uri.ToString()
                }).ToList();
                itm.SupportedProfile = ExtensionUtil.ProfileHandlers.Where(o => o.AppliesTo == null || o.AppliesTo.Contains(itm.Type.Value)).Select(o => o.ProfileUri.ToString()).ToList();
            }
            return retVal;


        }
    }
}
